version: "3.8"

services:

  mosquitto:
    image: eclipse-mosquitto:latest
    volumes:
      - ./broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"

  mosquitto-exporter:
    image: hikhvar/mqtt2prometheus
    container_name: mosquitto-exporter
    ports:
      - "9323:9323"
    volumes:
      - "/home/ibrazqrj/Documents/MQTT/exporter-config.yaml:/config/config.yaml"
    environment:
      - MQTT_BROKER=tcp://mosquitto:1883
    depends_on:
      - mosquitto

  sensor1:
    image: java-sensor:1.0 
    depends_on:
      - mosquitto
    environment:
      - MQTT_SERVER=mosquitto
      - MQTT_PUB_TOPIC=sensoren/java1
      - MQTT_SUB_TOPIC=feedback/java1

  sensor2:
    image: java-sensor:1.0 
    depends_on:
      - mosquitto
    environment:
      - MQTT_SERVER=mosquitto
      - MQTT_PUB_TOPIC=sensoren/java2
      - MQTT_SUB_TOPIC=feedback/java2

  sensor3:
    image: java-sensor:1.0 
    depends_on:
      - mosquitto
    environment:
      - MQTT_SERVER=mosquitto
      - MQTT_PUB_TOPIC=sensoren/java3
      - MQTT_SUB_TOPIC=feedback/java3

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3100:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - mosquitto
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - cadvisor

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys:/sys
      - /var/lib/docker/:/var/lib/docker:ro

volumes:
  grafana_data:
